# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/index.html'
    weight: 10
  - name: News
    url: '/news.html'
    weight: 20
  - name: Publications
    url: '/publication.html'
    weight: 30
  - name: Blog
    url: 'https://ananyamalikk.substack.com/'
    weight: 30
  - name: CV
    url: 'files/cv/Ananya_Resume_2023.pdf'
    weight: 30
  # - name: Projects
  #   url: '/project.html'
  #   weight: 30
