title: Ananya Malik
url: "https://ananyamalik.github.io/"
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

remote_theme: ankitsultana/researcher@gem
# tracking_id: #

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://ananyamalik.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link:  "https://ananyamalikk.substack.com/"